### ISSUE TITLE
Generated operators not generated if using Java 1.7

### ISSUE THREAD

**Issue by pcbye** [IBMStreams/streamsx.inet#224]
I am using Streams 4.2, did not go back to see if older versions of Streams made a difference.

When building the toolkit from a clean source tree (running "ant release"), if JAVA_HOME and JRE_HOME are set to a Java 1.7 based Java installation (e.g. /opt/ibm/java-x86_64-71 and /opt/ibm/java-x86_64-71/jre respectively), the toolkit build completes successfully, but generated operators such as HTTPTupleView do not get created.

If I run the same build but set JAVA_HOME and JRE_HOME to a Java 1.8 based java installation  (e.g. /opt/ibm/java-x86_64-80 and /opt/ibm/java-x86_64-80/jre respectively), the generated operators such as HTTPTupleView do get created.

It may be that with later versions of Streams that only support Java 1.8, we should not use Java 1.7 to build the toolkit.  But in all cases, the toolkit build should probably fail if the generated operators are not created (or at least produce some sort of warning - but a failure would be better if there is a hard requirement).

**Comment by chanskw** [comment]
I think this needs to get looked at.
Streams 4.2 only supports Java 1.8.

However, the master branch of the toolkit, states that the min streams version is 4.0.0 which supports 1.7.  I am curious as to what happens when we try to build this with 1.7 and Streams 4.0.  If that works, then I think this defect is invalid.  Otherwise, there is something wrong with the toolkit build set up.

**Comment by joergboe** [comment]
The build fails if build was called with java 7
