### ISSUE TITLE
Need getting started development guide on how to extend the Inet toolkit

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.inet#85]
See this question here:
https://developer.ibm.com/answers/questions/169767/article-regarding-toolkit-development.html#answer-169772

I have written a getting started guide for messaging toolkit and HDFS.  Please check it out and see  if it applies to Inet.  If not, please copy and fix, or write something up to help new user get started.

Thanks...

**Comment by hildrum** [comment]
Rather than adding a special-purpose "Getting started with Inet" page, I will modify the one in administration to add information about maven.  Here it is currently: 
https://github.com/IBMStreams/administration/wiki/Using-IBMStreams-from-Streams-Studio-%28draft%29

**Comment by hildrum** [comment]
After some thought, i figured it made sense to have two pages, one targeted after people who just want to build the toolkit and use it, and don't plan to share any development.  For that, I copied and pasted your page:
https://github.com/IBMStreams/administration/wiki/Building-and-using-a-toolkit-that-uses-Maven-to-handle-dependencies

And then, for people who are planning development, I'll link to the "Using IBMStreams from Streams Studio" page, since it contains some information about forking and branching.

Somewhere we should also add directions on how to get a 3.2.1 version of a toolkit.  I'm not sure whether I should add a section to the above pages, or create a separate page.

**Comment by chanskw** [comment]
I think for each project, we should have a wiki that describes our branching strategy and what streams we have.  We can talk about how to get to different branches on that page?

**Comment by chanskw** [comment]
I started a general branching strategy page here:
https://github.com/IBMStreams/administration/wiki/Toolkit-Branching-Guidelines-to-support-Streams-3.2.2-Beta

**Comment by hildrum** [comment]
I edited the toolkit branching page to add some "how to use an older branch" info;  it just has the command-line info; I'll try and add some info on how to do that from eclipse tomorrow.  We could move that to a separate page if you don't think it belongs there.    

I do think it makes sense for each toolkit to list which branches it has, and link to the how-to pages, many of which could be shared.  I lean towards making that first landing page the readme, and then have the top-level wiki page point to the readme.

**Comment by joergboe** [comment]
Hints are in:
DEVELOPMENT.md
